import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { api } from './api'
import './index.css'

const money = (n) => `₹${Number(n || 0).toLocaleString('en-IN')}`
const tone = (p) => ['cream', 'gold', 'lavender', 'orange', 'blue', 'green', 'brown'][p.id % 7]

function App() {
  const [stores, setStores] = useState([]), [storeId, setStoreId] = useState(1)
  const [products, setProducts] = useState([]), [query, setQuery] = useState('')
  const [category, setCategory] = useState('All'), [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('KhojMart_cart') || '[]'))
  const [view, setView] = useState('shop'), [notice, setNotice] = useState(''), [detail, setDetail] = useState(null)
  const [recommendations, setRecommendations] = useState([]), [comparison, setComparison] = useState([])
  const [lists, setLists] = useState([]), [orders, setOrders] = useState([]), [demands, setDemands] = useState([])
  const [demandOpen, setDemandOpen] = useState(false), [demandForm, setDemandForm] = useState({ item_name: '', category: '', notes: '' })
  useEffect(() => {
    api.stores().then(setStores).catch(e => setNotice(e.message)); api.recommendations().then(setRecommendations).catch(() => {})
    const load = () => Promise.all([api.lists(), api.orders(), api.demands()]).then(([saved, history, requested]) => { setLists(saved); setOrders(history); setDemands(requested) })
    load().catch(() => api.login({ email: 'customer@example.com', password: 'customer123' }).then(r => { localStorage.setItem('KhojMart_token', r.access_token); return load() }).catch(e => setNotice(e.message)))
  }, [])
  useEffect(() => { if (storeId) api.products(storeId, { search: query, category: category === 'All' ? '' : category }).then(setProducts).catch(e => setNotice(e.message)) }, [storeId, query, category])
  useEffect(() => localStorage.setItem('KhojMart_cart', JSON.stringify(cart)), [cart])
  const current = stores.find(s => s.id === storeId), categories = ['All', ...new Set(products.map(p => p.category))]
  const totalItems = cart.reduce((n, p) => n + p.quantity, 0), total = cart.reduce((n, p) => n + p.price * p.quantity, 0)
  const add = (p) => setCart(items => { const old = items.find(i => i.product_id === p.product_id); if (old && old.quantity >= p.quantity) { setNotice('Stock limit reached'); return items }; return old ? items.map(i => i.product_id === p.product_id ? { ...i, quantity: i.quantity + 1 } : i) : [...items, { product_id: p.product_id, name: p.name, price: p.price, image: p.image, stock: p.quantity, quantity: 1 }] })
  const change = (id, amount) => setCart(items => items.flatMap(i => i.product_id !== id ? [i] : i.quantity + amount > 0 && i.quantity + amount <= i.stock ? [{ ...i, quantity: i.quantity + amount }] : amount < 0 ? [] : [i]))
  const checkout = async () => { if (!cart.length) return; try { if (!localStorage.getItem('KhojMart_token')) { const login = await api.login({ email: 'customer@example.com', password: 'customer123' }); localStorage.setItem('KhojMart_token', login.access_token) }; await api.order({ store_id: storeId, items: cart.map(i => ({ product_id: i.product_id, quantity: i.quantity })) }); setCart([]); setNotice('Order placed — inventory updated'); api.orders().then(setOrders); api.products(storeId).then(setProducts) } catch (e) { setNotice(e.message) } }
  const saveCurrentList = async () => { if (!cart.length) return setNotice('Add items to your basket first'); const name = window.prompt('Name this shopping list', 'Weekly grocery'); if (!name?.trim()) return; try { const saved = await api.saveList({ name: name.trim(), items: cart.map(i => ({ product_id: i.product_id, quantity: i.quantity })) }); setLists(previous => [...previous, saved]); setNotice('Shopping list saved') } catch (e) { setNotice(e.message) } }
  const addList = (list) => { list.items.forEach(item => { const product = products.find(p => p.product_id === item.product_id); if (product) for (let n = 0; n < item.quantity; n += 1) add(product) }); setNotice('List added to basket where available') }
  const openDetail = (p) => { setDetail(p); api.comparison(p.product_id).then(setComparison).catch(() => setComparison([])) }
  const requestItem = (item = '') => { setDemandForm({ item_name: item, category: category === 'All' ? '' : category, notes: '' }); setDemandOpen(true) }
  const submitDemand = async (event) => {
    event.preventDefault()
    try {
      const saved = await api.saveDemand({ ...demandForm, store_id: storeId, category: demandForm.category || null, notes: demandForm.notes || null })
      setDemands(previous => [...previous, saved]); setDemandOpen(false); setDemandForm({ item_name: '', category: '', notes: '' }); setNotice('Request submitted to the store')
    } catch (e) { setNotice(e.message) }
  }
  return <div className="app">
    <header className="topbar"><button className="logo" onClick={() => setView('shop')}><span className="logo-mark">S</span><span>Khoj<span>Mart</span></span></button><nav><button className={view === 'shop' ? 'nav-active' : ''} onClick={() => setView('shop')}>Discover</button><button className={view === 'manager' ? 'nav-active' : ''} onClick={() => setView('manager')}>Manager view</button></nav><div className="top-actions"><span className="basket-count">Basket <b>{totalItems}</b></span><button className="avatar" onClick={() => setNotice('Signed in as Aarav Sharma')}>AS</button></div></header>
    {view === 'manager' ? <Manager setNotice={setNotice} /> : <main>
      <section className="hero"><div className="hero-copy"><span className="kicker">SMARTER SHOPPING, LESS SEARCHING</span><h1>Everything you need.<br /><i>Right where it is.</i></h1><p>Explore nearby stores, find the exact shelf, and keep your shopping trip moving.</p><button className="primary" onClick={() => document.querySelector('.catalog')?.scrollIntoView({ behavior: 'smooth' })}>Browse products ↗</button></div><div className="hero-visual"><div className="sun" /><div className="basket-art">🛍️</div><div className="floating-card card-top"><span>● LIVE INVENTORY</span><b>{products.reduce((n, p) => n + p.quantity, 0)}</b><small>units in stock</small></div></div></section>
      <section className="store-strip"><div className="section-label"><span className="kicker">NEARBY STORES</span><h2>Choose your store</h2></div><div className="store-list">{stores.map(s => <button className={`store-chip ${storeId === s.id ? 'store-selected' : ''}`} key={s.id} onClick={() => { setStoreId(s.id); setCategory('All') }}><span className="store-icon mint">✦</span><span><b>{s.name}</b><small>{s.type}</small></span><em>{s.distance} km</em></button>)}</div></section>
      <section className="catalog"><div className="catalog-head"><div><span className="kicker">{(current?.name || 'STORE').toUpperCase()} · OPEN NOW</span><h2>Find your next essential</h2></div><div className="search-box">⌕<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search products..." /></div></div><div className="category-bar">{categories.map(c => <button className={category === c ? 'category-active' : ''} key={c} onClick={() => setCategory(c)}>{c}</button>)}</div><div className="catalog-layout"><div className="product-grid">{products.map(p => <ProductCard key={`${p.product_id}-${p.store_id}`} p={p} add={add} open={openDetail} request={requestItem} />)}</div><Basket cart={cart} change={change} total={total} checkout={checkout} /></div>
      {recommendations.length > 0 && <section className="recommendations"><span className="kicker">JUST FOR YOU</span><h2>Recommended essentials</h2><div className="recommendation-row">{recommendations.slice(0, 4).map(p => <button key={p.id} onClick={() => setQuery(p.name)}>{p.image} {p.name}</button>)}</div></section>}
      <section className="customer-sections"><div className="customer-card"><div className="section-label"><div><span className="kicker">SAVED PLANS</span><h2>Shopping lists</h2></div><button className="secondary" onClick={saveCurrentList}>Save current basket</button></div>{lists.length ? lists.map(list => <div className="saved-row" key={list.id}><div><b>{list.name}</b><small>{list.items.length} products</small></div><button onClick={() => addList(list)}>Add all</button></div>) : <p className="muted">Save your weekly basket for a faster next trip.</p>}</div><div className="customer-card"><div className="section-label"><div><span className="kicker">ORDER TRACKING</span><h2>Order history</h2></div></div>{orders.length ? orders.slice().reverse().map(order => <div className="saved-row" key={order.id}><div><b>Order #{order.id}</b><small>{new Date(order.created_at).toLocaleString()} · {order.items.length} items</small></div><strong>{money(order.total)}</strong><span className="order-status">Placed</span></div>) : <p className="muted">Your completed orders will appear here.</p>}</div></section><section className="customer-card demand-section"><div className="section-label"><div><span className="kicker">STORE REQUESTS</span><h2>Demand an item</h2></div><button className="secondary" onClick={() => requestItem()}>Request this item</button></div><p className="muted">Can’t find it? Tell {(current?.name || 'this store')} what you would like stocked.</p>{demands.length ? demands.slice().reverse().map(d => <div className="saved-row" key={d.id}><div><b>{d.item_name}</b><small>{d.category || 'General'} · {new Date(d.created_at).toLocaleDateString()}</small></div><span className="order-status">{d.status}</span></div>) : <p className="muted">Your submitted requests and their status will appear here.</p>}</section></section>
    </main>}
    {detail && <div className="modal" onClick={() => setDetail(null)}><article onClick={e => e.stopPropagation()}><button className="close" onClick={() => setDetail(null)}>×</button><div className="detail-art">{detail.image}</div><span className="kicker">{detail.category}</span><h2>{detail.name}</h2><p>{detail.description}</p><p className="expiry-detail">Expiry date: <b>{detail.expiry || 'Not applicable'}</b></p><strong>{money(detail.price)}</strong>{detail.quantity ? <button className="primary" onClick={() => { add(detail); setDetail(null) }}>Add to basket</button> : <button className="primary" onClick={() => { requestItem(detail.name); setDetail(null) }}>Request this item</button>}{comparison.length > 1 && <div className="compare"><h3>Compare nearby stores</h3>{comparison.map(x => <div key={x.store_id}><span>Store {x.store_id}</span><b>{money(x.price)} · {x.quantity} available</b></div>)}</div>}</article></div>}
    {demandOpen && <div className="modal" onClick={() => setDemandOpen(false)}><form className="demand-form" onSubmit={submitDemand} onClick={e => e.stopPropagation()}><button type="button" className="close" onClick={() => setDemandOpen(false)}>×</button><span className="kicker">REQUEST FOR {(current?.name || 'STORE').toUpperCase()}</span><h2>What should we stock?</h2><input required minLength="2" maxLength="100" value={demandForm.item_name} onChange={e => setDemandForm({ ...demandForm, item_name: e.target.value })} placeholder="Item name" /><input maxLength="60" value={demandForm.category} onChange={e => setDemandForm({ ...demandForm, category: e.target.value })} placeholder="Category (optional)" /><textarea maxLength="500" value={demandForm.notes} onChange={e => setDemandForm({ ...demandForm, notes: e.target.value })} placeholder="Notes, brand or preferred quantity (optional)" /><button className="primary" type="submit">Submit request</button></form></div>}
    {notice && <button className="notice" onClick={() => setNotice('')}>✓ {notice} <b>×</b></button>}
  </div>
}
function ProductCard({ p, add, open, request }) { const status = p.quantity === 0 ? 'Out of stock' : p.quantity <= p.minimum_stock ? 'Low stock' : 'In stock'; return <article className="product-card"><button className={`product-art ${tone(p)}`} onClick={() => open(p)}><span>{p.image}</span><label className={status === 'Out of stock' ? 'sold-out' : ''}>{status}</label></button><div className="product-info"><div className="product-top"><span>{p.category}</span><span>★ {p.rating || '4.5'}</span></div><h3>{p.name}</h3><p className="location">⌖ Aisle {p.aisle} <i>·</i> Shelf {p.shelf}</p><p className="expiry">Expiry: {p.expiry || 'Not applicable'}</p><div className="product-price"><strong>{money(p.price)}</strong><small>{p.quantity ? `${p.quantity} available` : 'Come back soon'}</small></div><button onClick={() => p.quantity ? add(p) : request(p.name)}>{p.quantity ? '+ Add to basket' : 'Request this item'}</button></div></article> }
function Basket({ cart, change, total, checkout }) { return <aside className="shopping-panel"><div className="panel-heading"><div><span className="kicker">YOUR BASKET</span><h2>Weekly grocery</h2></div>🛒</div>{cart.length ? cart.map(i => <div className="basket-item" key={i.product_id}><span className="mini-art">{i.image}</span><div><b>{i.name}</b><small>{money(i.price)} each</small></div><div className="quantity"><button onClick={() => change(i.product_id, -1)}>−</button><span>{i.quantity}</span><button onClick={() => change(i.product_id, 1)}>+</button></div></div>) : <div className="basket-empty"><span>✦</span><p>Your basket is waiting.</p><small>Add products to plan your trip.</small></div>}<div className="panel-total"><span>Estimated total</span><strong>{money(total)}</strong></div><button className="checkout" onClick={checkout}>Complete purchase →</button></aside> }
function Manager({ setNotice }) { const [stats, setStats] = useState(null), [items, setItems] = useState([]), [demands, setDemands] = useState([]); const load = () => Promise.all([api.dashboard(), api.managerProducts(), api.managerDemands()]).then(([d, p, requested]) => { setStats(d); setItems(p); setDemands(requested) }); useEffect(() => { load().catch(() => api.login({ email: 'manager@example.com', password: 'manager123' }).then(r => { localStorage.setItem('KhojMart_token', r.access_token); return load() }).catch(e => setNotice(e.message))) }, []); const restock = async (item) => { try { const updated = await api.updateInventory(item.id, { quantity: item.quantity + 10, minimum_stock: item.minimum_stock, expiry: item.expiry, section: item.section, aisle: item.aisle, shelf: item.shelf, position: item.position }); setItems(old => old.map(x => x.id === item.id ? { ...x, ...updated } : x)); setNotice(`${item.name} restocked`) } catch (e) { setNotice(e.message) } }; return <main className="manager-view"><div className="manager-intro"><div><span className="kicker">FRESH MART · OPERATIONS</span><h1>Good morning, Maya.</h1><p>A clear view of what needs attention today.</p></div></div><div className="stat-grid">{[['PRODUCTS', stats?.total_products], ['TOTAL STOCK', stats?.total_stock], ['LOW STOCK', stats?.low_stock], ['NEAR EXPIRY', stats?.near_expiry]].map(([label, value]) => <div key={label}><small>{label}</small><b>{value ?? '—'}</b><span>live from inventory</span></div>)}</div><section className="inventory-table"><div className="table-title"><div><span className="kicker">INVENTORY HEALTH</span><h2>Products to watch</h2></div></div>{items.map(i => <div className="inventory-row" key={i.id}><span className="row-art mint">{i.image}</span><div><b>{i.name}</b><small>{i.category} · Aisle {i.aisle}</small></div><strong>{i.quantity} units</strong><label className={i.inventory_status !== 'NORMAL' ? 'warning' : ''}>{i.inventory_status}</label><button onClick={() => restock(i)}>+10</button></div>)}</section><section className="inventory-table demand-manager"><div className="table-title"><div><span className="kicker">CUSTOMER DEMANDS</span><h2>Requested items</h2></div></div>{demands.length ? demands.map(d => <div className="inventory-row" key={d.id}><span className="row-art mint">✦</span><div><b>{d.item_name}</b><small>{d.category || 'General'}{d.notes ? ` · ${d.notes}` : ''}</small></div><label>{d.status}</label></div>) : <p className="muted">No customer requests for this store yet.</p>}</section></main> }
createRoot(document.getElementById('root')).render(<App />)
